version: "2"
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
  sensor:
    build: .
#    image: cbernet/iot_dummy_sensor
    links:
      - influxdb
  dashboard:
    image: proxx/grafana-armv7
    links:
      - sensor
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana

volumes:
  influxdb:
  grafana:
