version: "3"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
#    networks:
#      - net
#  test:
#    image: testapp
#    container_name: test
#    networks:
#      - net
  sensor:
    build: .
    container_name: sensor
#    links:
#      - influxdb
#    networks:
#      - net

volumes:
  influxdb:
  
#networks:
#  net:

